image: "python:3.11.4"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  script:
    - echo test
#    - pip install -r requirements.txt
#    - docker build -t app:$CI_COMMIT_SHORT_SHA .
upload_job:
  stage: upload
  script:
    - echo test

#upload_job:
#  stage: upload
#  script:
#    - git remote set-url origin "${CI_REPOSITORY_URL}"
#    - kind load docker-image app:${CI_COMMIT_SHORT_SHA}
