image: "python:3.11.4"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login registry.gitlab.com
    - docker build -t app:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE

upload_job:
  stage: upload
  script:
    - echo test
