stages:
  - build
  - upload
  - deploy

build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - app/*
        - app/**/*
  script:
    - docker build -t app:$CI_COMMIT_SHORT_SHA .

upload_job:
  stage: upload
  script:
    - git remote set-url origin "${CI_REPOSITORY_URL}"
    - kind load docker-image app:${CI_COMMIT_SHORT_SHA}
