image: "python:3.11.4"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY-PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t lab8devops/app:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE

upload_job:
  stage: upload
  script:
    - echo test
