stages:
  - build
  - upload
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN <your_registry_address>

build:
  stage: build
  script:
    - docker build -t lab8devops .

upload:
  stage: upload
  script:
    - docker push lab8devops

deploy:
  stage: deploy
  script:
    - docker pull lab8devops
    - docker run -d -p 8080:80 --name app lab8devops