stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - app/*
        - app/**/*
  script:
    - cd app
    - pylint -d C0301 app.py
    - docker build -t app:$CI_COMMIT_SHORT_SHA .


upload_job:
  stage: upload
  script:
    - echo test


#deploy_job:
#  stage: deploy
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      changes:
#        - app/*
#        - app/**/*
#  script:
#    - mv ./pages ./public
#    - mv ./${TEXTBOOK_OUTPUT_DIRECTORY} ./public/documents
#    - mv ./presentations ./public/presentations
#    - rm -rf ${DEPLOY_DIR}/*
#    - cp -r ./public/. ${DEPLOY_DIR}/.
