#image: "docker:latest"

stages:
  - build
  - upload
#  - deploy

#neeed
build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd app
    - docker build -t lab8devops:${CI_COMMIT_SHORT_SHA} .

upload_job:
  stage: upload
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --update curl
    - curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.7.0/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - docker login -u vesha13 -p docker123
    - docker pull kindest/node:v1.27.3
    - kind create cluster #--name lab8
    - kind load docker-image docker.io/library/lab8devops:$CI_COMMIT_SHORT_SHA #--name lab8


#upload_job:
#  stage: upload
#  image: kindest/node:v1.27.3
#  services:
#    - docker:dind
#  script:
#    #- docker pull kindest/node:v1.27.3
#    - kind create cluster --name lab8
#    - kind load docker-image lab8devops${CI_COMMIT_SHORT_SHA} --name lab8

# deploy_job:
#   environment:
#     name: production
#   script:
#     - kubectl get pods