stages:
  - build
  - upload
  - deploy
build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd app
    - docker build -t lab8devops:${CI_COMMIT_SHORT_SHA} .
    - docker images
upload_job:
  stage: upload
  image: docker:stable
  services:
    - docker:dind
  script:
    - apk add --update curl
    - curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.7.0/kind-linux-amd64
    - chmod +x /usr/local/bin/kind
    - docker login -u vesha13 -p docker123
    - docker pull kindest/node:v1.27.3
    - kind create cluster --name lab8
deploy_job:
  stage: deploy
  environment:
     name: production
  image: docker:stable
  script:
    - apk add --update curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x /usr/local/bin/kubectl
    - kubectl get pods