image: "python:3.11.4"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    #- echo "$Ci_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password "$Ci_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker login -u "glptt-f26648bd0c658b78377f6a9d5440545fa9f31363" -p
    #- echo $Ci_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t app:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE

upload_job:
  stage: upload
  script:
    - echo test
