image: "docker:latest"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd app
    - docker build -t lab8devops/app:$CI_COMMIT_SHORT_SHA .


upload_job:
  stage: upload
  script:
    - kind load docker-image lab8devops/app:${CI_COMMIT_SHORT_SHA}
