stages:
  - build
  - upload
  - deploy

build_job:
  stage: build
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      changes:
#        - app/*
#        - app//*
  script:
    - cd app
    - pylint -d C0301 app.py
    - docker build -t app:$CI_COMMIT_SHORT_SHA .


upload:
  stage: upload
  script:
    - lab8devops load docker-image app:${CI_COMMIT_SHORT_SHA}
