image: "python:3.11.4"

stages:
  - build
  - upload
#  - deploy

build_job:
  stage: build
  script:
    - pip install -r requirements.txt
    - docker build -t lab8devops/app:$CI_COMMIT_SHA .

upload_job:
  stage: upload
  script:
    - echo test
