#image: "docker:latest"

stages:
  # - build +
  - upload
#  - deploy

#neeed
#build_job:
#  stage: build
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
#    - cd app
#    - docker build -t lab8devops:$CI_COMMIT_SHORT_SHA .

upload_job:
  stage: upload
  image: sha256:0911803a52993675d7d784fc60a1b32cddb08bfc16f527a6395af4cc919baf9a
#  services:
#    - docker:dind
  script:
    #- docker pull kindest/node:v1.27.3
    - kind create cluster --name lab8
    - kind load docker-image lab8devops${CI_COMMIT_SHORT_SHA} --name lab8

# deploy_job:
#   environment:
#     name: production
#   script:
#     - kubectl get pods