services:
  app:
    image: lab8devops
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lab8devops
    networks:
      - lab8devops
    ports:
      - 8080:5000
    environment:
      - APP_SERVICE_NAME=lab8devops-app
networks:
  lab8devops: